# Generated by Django 3.0.6 on 2020-06-03 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0003_auto_20200531_2230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-pub_date']},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='photo',
        ),
        migrations.AlterField(
            model_name='image',
            name='photo_comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pics.Comments'),
        ),
        migrations.AlterField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pics.Profile'),
        ),
    ]
