# Generated by Django 3.0.6 on 2020-06-03 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_auto_20200603_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='profile',
        ),
        migrations.AddField(
            model_name='comments',
            name='photo',
            field=models.ForeignKey(default='3', on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='pics.Image'),
        ),
    ]
